/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testibus.lib.src.test.java.testibus;

import org.junit.jupiter.api.Test;
import testibus.Library;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        Assertions.assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
