/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testibus.lib.src.main.java.testibus;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
